spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hublog
    username: root
    password: root
  jpa: 
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

server:
  context-path: /hublog
      